# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel.
version: 3.0.x-{build}

clone_folder: c:\projects\ec-cube

cache:
  - '%LOCALAPPDATA%\Composer\files'
  - vendor

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

environment:
  global:
    USER: "root"
    DBNAME: "myapp_test"
    DBPASS: "Password12!"
    DBUSER: "root"
    BASE_DIR: "C:/projects/ec-cube"

  matrix:
  - db: mysql
    provider: mysql

services:
  - mysql

# Install scripts. (runs after repo cloning)
install:
  - cp phpunit.xml.dist phpunit.xml
  # see https://github.com/phpmd/phpmd/blob/master/appveyor.yml#L10-L13
  - cinst -y OpenSSL.Light --version 1.1.1
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  # Set MySQL.
  - cp tests/my.cnf c:\
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.7\bin\;%PATH%
  #- cinst mysql
  #- SET PATH=C:\tools\mysql\current\bin\;%PATH%
  # Set PHP.
  - cinst php --version 7.1.20 --allow-empty-checksums
  - SET PATH=C:\tools\php71\;%PATH%
  - copy C:\tools\php71\php.ini-production C:\tools\php71\php.ini
  - echo date.timezone="Asia/Tokyo" >> C:\tools\php71\php.ini
  - echo extension_dir=ext >> C:\tools\php71\php.ini
  - echo extension=php_openssl.dll >> C:\tools\php71\php.ini
  - echo extension=php_gd2.dll >> C:\tools\php71\php.ini
  - echo extension=php_mbstring.dll >> C:\tools\php71\php.ini
  - echo extension=php_pgsql.dll >> C:\tools\php71\php.ini
  - echo extension=php_pdo_mysql.dll >> C:\tools\php71\php.ini
  - echo extension=php_pdo_pgsql.dll >> C:\tools\php71\php.ini
  - echo extension=php_curl.dll >> C:\tools\php71\php.ini
  - echo extension=php_fileinfo.dll >> C:\tools\php71\php.ini
  - echo memory_limit = 512M >> C:\tools\php71\php.ini
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --dev --no-interaction -o

# Don't actually build.
build: off

before_test:
  - php eccube_install.php mysql none

test_script:
  - vendor\bin\phpunit.bat -c phpunit.xml
